version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "6603:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    restart: always
    depends_on:
      - db
    ports:
      - "9100:5000"
    environment:
      DB_HOST: db
      DB_PORT: 6603
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: test
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:9100
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
